sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - pypy3
  - 3.3
  - 3.4
  - 3.5
matrix:
  include:
    - python: 2.7
      env: MINREQ=1

    - python: 2.7
      env: TABULATE_VERSION=dev

    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - python-tabulate
            - python-texttable
            - python-requests
            - python-coverage
before_install:
  - if [[ "$TABULATE_VERSION" = "dev" ]]; then
      pip install git+https://bitbucket.org/astanin/python-tabulate ;
      echo > README.rst ;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - pip install --upgrade setuptools "pip==7.1"
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
